# Generated by Django 4.1.4 on 2022-12-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alter_ego', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('editorial', models.CharField(choices=[('dc', 'DC'), ('marvel', 'Marvel'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
            ],
        ),
    ]
